function sqlString(value) {
  if (value == null) {
    return "NULL";
  }
  const text = String(value).replace(/'/g, "''");
  return `'${text}'`;
}

function sqlNumber(value) {
  if (value == null || Number.isNaN(Number(value))) {
    return "NULL";
  }
  return String(Number(value));
}

function insertCycles(lines, cycles) {
  for (const cycle of cycles) {
    lines.push(
      `INSERT INTO cycles (cycle_id, session_id, state, outcome, branch_name, dor_state, continuity_rule, continuity_base_branch, continuity_latest_cycle_branch, updated_at) VALUES (${sqlString(cycle.cycle_id)}, ${sqlString(cycle.session_id)}, ${sqlString(cycle.state)}, ${sqlString(cycle.outcome)}, ${sqlString(cycle.branch_name)}, ${sqlString(cycle.dor_state)}, ${sqlString(cycle.continuity_rule)}, ${sqlString(cycle.continuity_base_branch)}, ${sqlString(cycle.continuity_latest_cycle_branch)}, ${sqlString(cycle.updated_at)});`,
    );
  }
}

function insertArtifacts(lines, artifacts) {
  for (const artifact of artifacts) {
    lines.push(
      `INSERT INTO artifacts (path, kind, sha256, size_bytes, mtime_ns, session_id, cycle_id, updated_at) VALUES (${sqlString(artifact.path)}, ${sqlString(artifact.kind)}, ${sqlString(artifact.sha256)}, ${sqlNumber(artifact.size_bytes)}, ${sqlNumber(artifact.mtime_ns)}, ${sqlString(artifact.session_id)}, ${sqlString(artifact.cycle_id)}, ${sqlString(artifact.updated_at)});`,
    );
  }
}

function insertFileMap(lines, fileMap) {
  for (const row of fileMap) {
    lines.push(
      `INSERT INTO file_map (cycle_id, path, role, last_seen_at) VALUES (${sqlString(row.cycle_id)}, ${sqlString(row.path)}, ${sqlString(row.role)}, ${sqlString(row.last_seen_at)});`,
    );
  }
}

function insertTags(lines, tags) {
  for (const tag of tags) {
    lines.push(`INSERT INTO tags (tag) VALUES (${sqlString(tag.tag)});`);
  }
}

function insertArtifactTags(lines, artifactTags) {
  for (const row of artifactTags) {
    lines.push(
      `INSERT INTO artifact_tags (artifact_id, tag_id) SELECT a.artifact_id, t.tag_id FROM artifacts a, tags t WHERE a.path = ${sqlString(row.path)} AND t.tag = ${sqlString(row.tag)};`,
    );
  }
}

export function buildSqlFromIndex(indexData, options = {}) {
  const includeSchema = options.includeSchema !== false;
  const schemaText = (options.schemaText ?? "").trim();
  const lines = [];
  lines.push("-- Generated by tools/perf/index-to-sql.mjs");
  lines.push("-- Source of truth remains Markdown files; this SQL is a derived import format.");
  lines.push("PRAGMA foreign_keys=OFF;");
  lines.push("BEGIN TRANSACTION;");
  lines.push("");

  if (includeSchema) {
    lines.push("-- Schema");
    lines.push(schemaText.endsWith(";") ? schemaText : `${schemaText};`);
    lines.push("");
  }

  lines.push("-- Clean existing rows");
  lines.push("DELETE FROM artifact_tags;");
  lines.push("DELETE FROM tags;");
  lines.push("DELETE FROM file_map;");
  lines.push("DELETE FROM artifacts;");
  lines.push("DELETE FROM cycles;");
  lines.push("DELETE FROM run_metrics;");
  lines.push("");

  const cycles = Array.isArray(indexData.cycles) ? indexData.cycles : [];
  const artifacts = Array.isArray(indexData.artifacts) ? indexData.artifacts : [];
  const fileMap = Array.isArray(indexData.file_map) ? indexData.file_map : [];
  const tags = Array.isArray(indexData.tags) ? indexData.tags : [];
  const artifactTags = Array.isArray(indexData.artifact_tags) ? indexData.artifact_tags : [];

  lines.push("-- Insert data");
  insertCycles(lines, cycles);
  insertArtifacts(lines, artifacts);
  insertFileMap(lines, fileMap);
  insertTags(lines, tags);
  insertArtifactTags(lines, artifactTags);

  lines.push("");
  lines.push("COMMIT;");
  lines.push("PRAGMA foreign_keys=ON;");
  lines.push("");
  return `${lines.join("\n")}\n`;
}
